# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FlowControllerDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FlowControllerDemo
  pod 'ReactiveCocoa', '~> 6.0.2'

  target 'FlowControllerDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FlowControllerDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
